### ISSUE TITLE
base64-url vulnerability

### ISSUE THREAD

**Issue by soarcreator** [webcc/cassandra-store#10]
There was a report about the vulnerability of base64-url which is imported by this module.
https://hackerone.com/reports/321692
It has been solved since its version 2.0.
I want you to update the dependencies of this module if you can.
I think there will be no problem even if it uses the latest cassandra-driver and express-session.
I exchanged them with the latest locally, but it seems to be working fine.

**Comment by darthcav** [comment]
Fixed in version 5.0.0
