### ISSUE TITLE
In the readme, the link to the datastack docs shows a "Forbidden" error

### ISSUE THREAD

**Issue by jenswegar** [webcc/cassandra-store#2]
The following link in the readme returns with a 403 error
http://www.datastax.com/documentation/developer/nodejs-driver/2.0/nodejs-driver/

<img width="662" alt="screen shot 2015-11-10 at 10 00 54" src="https://cloud.githubusercontent.com/assets/647808/11057222/fb307446-8791-11e5-96b3-9e509f072ddc.png">

Also, it looks like the server would support https-connections, so maybe change to that at the same time?

**Comment by darthcav** [comment]
Fixed by https://github.com/webcc/cassandra-store/commit/413ffc9452094c354453d4e93c4464dbc40a9a6c
